spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  authorization:
    enabled: true
#    Admin-user must exist in your okta tenant already
  admin-user:
    id : amar.deep.singh@xyz.com
    firstName: Amar Deep
    lastName: Singh
    email: amar.deep.singh@xyz.com
  filter:
    create: All Tasks
  generic-properties:
    properties:
      generalResourceWhitelistPattern: ".+"
# Spring security configurations for okta authorization server
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: change it
            client-secret: change it
            scope: openid,profile,email
        provider:
          okta:
            authorization-uri: https://CHANGEIT.okta.com/oauth2/default/v1/authorize
            token-uri: https://CHANGEIT.okta.com/oauth2/default/v1/token
            user-info-uri: https://CHANGEIT.okta.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://CHANGEIT.okta.com/oauth2/default/v1/keys

# Flags for enabling/ disabling single logout
oauth2:
  enabled: true
#  groupNameAttribute matters a lot, it should be same as scope name and claim name. Defaults to groups
  groupNameAttribute: groups
  singlelogout:
    enabled: false
