spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  authorization:
    enabled: true
  # If you don't create it then Camunda will ask you to create one on First login
  admin-user:
    id: demo
    password: demo
okta:
  oauth2:
    #  Make sure to change the below as per your okta tenant
    issuer: https://<your-dev-tenant>.okta.com/oauth2/default
    client-id: <your okta client id here>
    client-secret: <your okta client secret here>
    scopes: openid,profile,email
    #Make sure you have created camunda-groups claim on okta authorization server
    groupsClaim: camunda-groups
    #  Make sure to change the below as per your okta tenant
    orgUrl: https://<your-dev-tenant>.okta.com
    postLogoutRedirectUri: http://localhost:8080/