spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  authorization:
    enabled: true
#    Admin-user must exist in your okta tenant already
  admin-user:
    id : amar.deep.singh@xyz.com
    firstName: Amar Deep
    lastName: Singh
    email: amar.deep.singh@xyz.com

  generic-properties:
    properties:
      generalResourceWhitelistPattern: ".+"
# Spring security configurations for okta authorization server
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: <your client-id here>
            client-secret: <your client-secret here>
            scope: openid,profile,email,groups
        provider:
          okta:
            authorization-uri: https://yourtenent.okta.com/oauth2/default/v1/authorize
            token-uri: https://yourtenent.okta.com/oauth2/default/v1/token
            user-info-uri: https://yourtenent.okta.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://yourtenent.okta.com/oauth2/default/v1/keys

# Flags for enabling/ disabling single logout
oauth2:
  enabled: false
#  groupNameAttribute matters a lot, it should be same as scope name and claim name. Defaults to groups
  groupNameAttribute: groups
  singlelogout:
    enabled: false
