spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  authorization:
    enabled: true
#    Admin-user must exist in your okta tenant already
  admin-user:
    id : amar.deep.singh@xyz.com
    firstName: Amar Deep
    lastName: Singh
    email: amar.deep.singh@xyz.com

  generic-properties:
    properties:
      generalResourceWhitelistPattern: ".+"
okta:
  oauth2:
    #  Make sure to change the below as per your okta tenant
    issuer: https://<your-dev-tenant>.okta.com/oauth2/default
    client-id: <your okta client id here>
    client-secret: <your okta client secret here>
    scopes: openid,profile,email
    #Make sure you have created camunda-groups claim on okta authorization server
    groupsClaim: camunda-groups
    #  Make sure to change the below as per your okta tenant
# The value of this flag activates single logout (clears okta session as well.)
sso:
  enable:
    singlelogout: true
